---

- name: create topdir
  file:
      dest={{ topdir }}
      state=directory
      mode=0755

- name: create pkgsdir
  file:
      dest={{ pkgsdir }}
      state=directory
      mode=0755

- name: create builddir
  file:
      dest={{ builddir }}
      state=directory
      mode=0755

- name: create outputdir
  file:
      dest={{ outputdir }}
      state=directory
      mode=0755
