---
# tasks file for ltp-ansible
  - import_tasks: common.yml

  - name: install dependencies on Ubuntu
    apt:
        name=autoconf,automake,m4,git
        state=present
    when: ansible_distribution == 'Ubuntu'

  - name: install dependencies on Deepin
    apt:
        name=autoconf,automake,m4,git,build-essential
        state=present
    when: ansible_distribution == 'Deepin GNU/Linux'

  - name: download ltp
    git:
        repo=https://github.com/linux-test-project/ltp.git
        dest={{ builddir }}/ltp
        version=20180118
        force=yes

  - name: build ltp
    shell:
        cd {{ builddir }}/ltp;
        make autotools;
        ./configure --prefix={{ installdir }};
        make -j{{ ansible_processor_count }};
        make install

  - name: run ltp
    shell:
      cd {{ installdir }};
      ./testscripts/ltpstress.sh -n -t 168
